
[general]
log_level_new="debug"
environment="dev_local"

[postgresql]
dsn="postgres://x:x@192.168.124.113:5432/stock-server?sslmode=disable"
log_sql=true

[http]
addr="0.0.0.0:8080"
enable_pprof=false
enable_prometheus=true

[aliyun_oss]
bucket="stock-server"
region="oss-cn-shenzhen"
key="x"
secret="x"
